/*
  Lesson 01 - Metadata,Read, add, and remove rows
  Student:a22509596
  Date: 18/09/2026
*/

USE ULHT_DB26;
GO

/*
SELECT * FROM sys.databases;
select * from INFORMATION_SCHEMA.SCHEMATA;

SELECT
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'Scott'
  AND TABLE_NAME = 'EMP'
ORDER BY ORDINAL_POSITION;

INSERT INTO Scott.EMP
    (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
    (2703, 'COURSE TEST', NULL, NULL, GETDATE(), 1000, NULL, NULL);
*/

-- EX 1 
SELECT DB_NAME() AS current_database;

-- EX2

SELECT
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS;

-- EX3

SELECT * 
FROM HR.EMPLOYEES Where LAST_NAME = 'SMITH';

-- EX 4
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE SALARY > 10000 AND DEPARTMENT_ID != 80;

-- A5. 
SELECT FIRST_NAME, LAST_NAME
FROM HR.EMPLOYEES
WHERE MANAGER_ID IS NULL;

-- A6. 
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID
FROM HR.DEPARTMENTS
WHERE DEPARTMENT_NAME = 'IT';

-- A6. 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = 60;

-- B1. 
SELECT EMPLOYEE_ID
FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = 703;

-- B2. 
SELECT COLUMN_NAME AS "Mandatory Columns"
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'HR' 
  AND TABLE_NAME = 'EMPLOYEES' 
  AND IS_NULLABLE = 'NO';

-- B3. 
INSERT INTO HR.EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, DEPARTMENT_ID)
VALUES (703, 'Luis', 'Gomes', '123.456.7890', '2026-09-15', 'IT_PROG', 20000.00, 60);

-- B3 
SELECT *
FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = 703;

-- C1. 
SELECT *
FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = 703;

-- C2. 
DELETE FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = 703;

-- C3. 
SELECT *
FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = 703;
